/-
Copyright (c) 2026 Re'em Melamed-Katz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Re'em Melamed-Katz
-/

import Mathlib.Algebra.Group.Pointwise.Set.Basic
import Mathlib.Algebra.Group.Hom.Basic
import Mathlib.Algebra.Group.Subsemigroup.Basic
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Data.Set.Finite.Range
import Mathlib.Data.Fintype.Basic
import Mathlib.Algebra.Group.Pointwise.Set.Finite
import Mathlib.Order.CompleteLattice.Finset
import Project.FactorizationForest.Combine
import Project.FactorizationForest.Forest

/-!
# Brown's Lemma and Algebraic Applications of Factorization Forests

This file formalizes the proof of Brown's Lemma.

## References
* [T. Colcombet, *The Factorization Forest Theorem*][colcombet2008]
-/

namespace BrownLemma

open Set FactorizationForest
open scoped Pointwise

variable {S T : Type*} [Semigroup S] [Semigroup T]

/-- The Simon complexity `nS S` of any non-empty finite semigroup `S` is strictly positive. -/
lemma nS_pos {S : Type*} [Semigroup S] [Fintype S] [Nonempty S] : 0 < nS S := by
  dsimp [nS]
  have h_ne : (Finset.univ.image (fun (x : S) ↦ nSElement x)).Nonempty := by
    obtain ⟨x⟩ : Nonempty S := inferInstance
    exact ⟨_, Finset.mem_image_of_mem _ (Finset.mem_univ x)⟩
  rw [dif_pos h_ne]
  obtain ⟨x⟩ : Nonempty S := inferInstance
  have h_pos : 0 < nSElement x := nSElement_pos x
  have h_mem : nSElement x ∈ Finset.univ.image (fun (x : S) ↦ nSElement x) :=
    Finset.mem_image_of_mem _ (Finset.mem_univ x)
  exact h_pos.trans_le (Finset.le_max' _ _ h_mem)

/-- `Fin (nS S)` is non-empty for any non-empty finite semigroup `S`. -/
instance instNonemptyFin_nS {S : Type*} [Semigroup S] [Fintype S] [Nonempty S] :
    Nonempty (Fin (nS S)) :=
  Fin.pos_iff_nonempty.mp nS_pos

/-- The inductive sequence of subsets $X_n \subseteq S$.
$X_0 = X$
$X_{n+1} = X_n \cup (X_n \cdot X_n) \cup \bigcup_{e \in T, e^2 = e}$
$\langle X_n \cap \phi^{-1}(e) \rangle_S$ -/
def X_seq (ϕ : S →ₙ* T) (X : Set S) : ℕ → Set S
  | 0 => X
  | n + 1 =>
    let Xn := X_seq ϕ X n
    Xn ∪ (Xn * Xn) ∪ ⋃ (e : T) (_ : e * e = e), (Subsemigroup.closure (Xn ∩ ϕ ⁻¹' {e}) : Set S)

/-- $X_n \subseteq X_{n+1}$ for all $n$. -/
lemma X_seq_succ_self (ϕ : S →ₙ* T) (X : Set S) (n : ℕ) :
    X_seq ϕ X n ⊆ X_seq ϕ X (n + 1) := by
  dsimp [X_seq]
  exact subset_union_left.trans subset_union_left

/-- $X_m \subseteq X_n$ whenever $m \le n$. -/
lemma X_seq_mono (ϕ : S →ₙ* T) (X : Set S) {m n : ℕ} (h : m ≤ n) :
    X_seq ϕ X m ⊆ X_seq ϕ X n := by
  induction h with
  | refl => exact subset_rfl
  | step hk ih => exact ih.trans (X_seq_succ_self ϕ X _)

/-- $X_n \subseteq \langle X \rangle_S$ for all $n$. -/
lemma X_seq_subset_closure (ϕ : S →ₙ* T) (X : Set S) (n : ℕ) :
    X_seq ϕ X n ⊆ Subsemigroup.closure X := by
  induction n with
  | zero => exact Subsemigroup.subset_closure
  | succ n ih =>
    dsimp [X_seq]
    refine union_subset (union_subset ih ?_) ?_
    · rintro _ ⟨a, ha, b, hb, rfl⟩
      exact Subsemigroup.mul_mem _ (ih ha) (ih hb)
    · simp only [iUnion_subset_iff, SetLike.coe_subset_coe, Subsemigroup.closure_le]
      grind

/-- A semigroup $S$ is locally finite if every finite subset generates a finite subsemigroup. -/
def IsLocallyFinite (S : Type*) [Semigroup S] : Prop :=
  ∀ (X : Set S), X.Finite → (Subsemigroup.closure X : Set S).Finite

/-- Product of a non-empty list of elements in a semigroup `S`. -/
def listProdNE : (u : List S) → u ≠ [] → S
  | [], hu => False.elim (hu rfl)
  | a :: rest, _ => rest.foldl (· * ·) a

lemma listProdNE_singleton (a : S) : listProdNE [a] (by simp) = a := rfl

lemma foldl_mul_eq_mul_listProdNE (x : S) (v : List S) (hv : v ≠ []) :
    v.foldl (· * ·) x = x * listProdNE v hv := by
  revert x
  induction v with
  | nil => contradiction
  | cons b rest ih =>
    intro x
    cases rest with
    | nil => rfl
    | cons c rest' =>
      have h_rest_ne : c :: rest' ≠ [] := by simp
      change List.foldl (· * ·) (x * b) (c :: rest') = x * List.foldl (· * ·) b (c :: rest')
      rw [ih h_rest_ne (x * b), ih h_rest_ne b, mul_assoc]

lemma listProdNE_concat (u v : List S) (hu : u ≠ []) (hv : v ≠ []) :
    listProdNE (u ++ v) (by simp [hu, hv]) = listProdNE u hu * listProdNE v hv := by
  cases u with
  | nil => contradiction
  | cons a rest =>
    dsimp [listProdNE]
    rw [List.foldl_append]
    exact foldl_mul_eq_mul_listProdNE (rest.foldl (· * ·) a) v hv

/-- Every element in `Subsemigroup.closure X` is generated by
a non-empty list of elements in `X`. -/
lemma mem_closure_iff_exists_list (X : Set S) (s : S) :
    s ∈ Subsemigroup.closure X ↔
    ∃ (u : List S) (hu : u ≠ []), (∀ x ∈ u, x ∈ X) ∧ listProdNE u hu = s := by
  constructor
  · intro hs
    induction hs using Subsemigroup.closure_induction with
    | mem x hx =>
      refine ⟨[x], by simp, by simp [hx], rfl⟩
    | mul x y hx hy ihx ihy =>
      rcases ihx with ⟨ux, hux, hX_x, rfl⟩
      rcases ihy with ⟨uy, huy, hX_y, rfl⟩
      refine ⟨ux ++ uy, by simp [hux, huy], ?_, listProdNE_concat ux uy hux huy⟩
      rintro a ha
      rcases List.mem_append.mp ha with h | h
      · exact hX_x a h
      · exact hX_y a h
  · rintro ⟨u, hu, hX, rfl⟩
    induction u with
    | nil => contradiction
    | cons a rest ih =>
      cases rest with
      | nil => exact Subsemigroup.subset_closure (hX a (by simp))
      | cons b rest' =>
        have h_rest_ne : b :: rest' ≠ [] := by simp
        have ih' := ih h_rest_ne (fun x hx ↦ hX x (List.mem_cons_of_mem a hx))
        have ha : a ∈ Subsemigroup.closure X := Subsemigroup.subset_closure (hX a (by simp))
        have h_eq : listProdNE (a :: b :: rest') hu = a * listProdNE (b :: rest') h_rest_ne := by
          dsimp [listProdNE]
          exact foldl_mul_eq_mul_listProdNE a (b :: rest') h_rest_ne
        rw [h_eq]
        exact Subsemigroup.mul_mem _ ha ih'

lemma listProdNE_eq (u v : List S) (hu : u ≠ []) (hv : v ≠ []) (h : u = v) :
    listProdNE u hu = listProdNE v hv := by
  cases h
  rfl

axiom valid_binary {A S} [Semigroup S] {eval : List A → S}
  {l r : FactorizationTree A} {w : List A} {h : ℕ} :
  IsRamseyTree eval (FactorizationTree.binary l r w h) →
  l.word ≠ [] ∧ r.word ≠ [] ∧ w = l.word ++ r.word ∧ l.height + 1 ≤ h ∧ r.height + 1 ≤ h

axiom valid_nary {A S} [Semigroup S] {eval : List A → S}
  {cs : List (FactorizationTree A)} {w : List A} {h : ℕ} :
  IsRamseyTree eval (FactorizationTree.nary cs w h) →
  cs ≠ [] ∧ (∀ c ∈ cs, c.word ≠ []) ∧ w = List.flatten
  (cs.map FactorizationTree.word) ∧ ∀ c ∈ cs, c.height + 1 ≤ h

/-- **Algebraic Presentation Theorem**:
For a semigroup morphism `ϕ : S →ₙ* T` to a finite semigroup `T` and generator set `X ⊆ S`,
the subsemigroup closure `⟨X⟩_S` coincides with the $X_{3 |T| - 1}$ step of the sequence. -/
theorem closure_eq_X_seq [Fintype T] [Nonempty T] (ϕ : S →ₙ* T) (X : Set S) :
    (Subsemigroup.closure X : Set S) = X_seq ϕ X (3 * nS T - 1) := by
  ext s
  constructor
  · intro hs
    rcases (mem_closure_iff_exists_list X s).mp hs with ⟨u, hu, huX, rfl⟩
    let eval_T : List S → T :=
      fun w ↦ if hw : w = [] then Classical.arbitrary T else ϕ (listProdNE w hw)
    have hmul_T : ∀ v w, v ≠ [] → w ≠ [] → eval_T (v ++ w) = eval_T v * eval_T w := by
      intros v w hv hw
      dsimp [eval_T]
      rw [dif_neg (by simp [hv, hw]), dif_neg hv, dif_neg hw]
      rw [listProdNE_concat v w hv hw]
      exact ϕ.map_mul (listProdNE v hv) (listProdNE w hw)
    have listProdNE_bind_closure (e : T) (Y : Set S) (cs_words : List (List S))
        (hcs : cs_words ≠ []) (h_all_ne : ∀ c ∈ cs_words, c ≠ [])
        (h_eval : ∀ c ∈ cs_words, eval_T c = e)
        (h_mem : ∀ (c : List S) (hc : c ∈ cs_words), listProdNE c (h_all_ne c hc) ∈ Y)
        (w : List S) (hw : w = cs_words.flatten) (hw_ne : w ≠ []) :
        listProdNE w hw_ne ∈ Subsemigroup.closure (Y ∩ ϕ ⁻¹' {e}) := by
      revert w
      induction cs_words with
      | nil => contradiction
      | cons c rest ih =>
        cases rest with
        | nil =>
          intro w hw hw_ne
          have h_eq : w = c := by
            dsimp [List.flatten] at hw
            exact (List.append_nil c).symm ▸ hw
          have h_prod_eq : listProdNE w hw_ne = listProdNE c (h_all_ne c (by simp)) :=
            listProdNE_eq w c hw_ne (h_all_ne c (by simp)) h_eq
          rw [h_prod_eq]
          apply Subsemigroup.subset_closure
          have hec : eval_T c = e := h_eval c (by simp)
          dsimp [eval_T] at hec
          rw [dif_neg (h_all_ne c (by simp))] at hec
          exact ⟨h_mem c (by simp), hec⟩
        | cons d rest' =>
          intro w hw hw_ne
          have h_rest_ne : d :: rest' ≠ [] := by simp
          have h_all_ne_rest : ∀ x ∈ d :: rest', x ≠ [] := fun x hx ↦ h_all_ne x (by simp [hx])
          have hw_rest_ne : (d :: rest').flatten ≠ [] := by
            intro h
            have : (d :: rest').flatten = d ++ (rest'.flatten) := rfl
            rw [this] at h
            exact h_all_ne_rest d (by simp) (List.append_eq_nil_iff.mp h).1
          have h_w' : ∃ w', w' = (d :: rest').flatten ∧ w' ≠ [] :=
            ⟨(d :: rest').flatten, rfl, hw_rest_ne⟩
          obtain ⟨w', hw', hw'_ne⟩ := h_w'
          have hw_eq : w = c ++ w' := by
            rw [hw, hw']
            rfl
          have h_prod_eq :
            listProdNE w hw_ne = listProdNE c (h_all_ne c (by simp)) * listProdNE w' hw'_ne := by
            have h_concat_ne : c ++ w' ≠ [] := by simp [h_all_ne c (by simp)]
            have h_eq1 : listProdNE w hw_ne = listProdNE (c ++ w') h_concat_ne :=
              listProdNE_eq w (c ++ w') hw_ne h_concat_ne hw_eq
            rw [h_eq1]
            exact listProdNE_concat c w' (h_all_ne c (by simp)) hw'_ne
          rw [h_prod_eq]
          apply Subsemigroup.mul_mem
          · apply Subsemigroup.subset_closure
            have hec : eval_T c = e := h_eval c (by simp)
            dsimp [eval_T] at hec
            rw [dif_neg (h_all_ne c (by simp))] at hec
            exact ⟨h_mem c (by simp), hec⟩
          · exact ih h_rest_ne
              (fun x hx ↦ h_all_ne x (List.mem_cons_of_mem c hx))
              (fun x hx ↦ h_eval x (List.mem_cons_of_mem c hx))
              (fun x hx ↦ h_mem x (List.mem_cons_of_mem c hx))
              w' hw' hw'_ne
    obtain ⟨t, ht_word, ht_height, ht_ramsey⟩ := factorization_forest eval_T hmul_T u hu
    have h_tree_mem_lem : ∀ n (t' : FactorizationTree S), t'.height ≤ n →
        (ht' : t'.word ≠ []) →
        (∀ x ∈ t'.word, x ∈ X) → IsRamseyTree eval_T t' →
        listProdNE t'.word ht' ∈ X_seq ϕ X t'.height := by
      intro n
      induction n with
      | zero =>
        intro t' h_height ht' hX h_ram
        cases t' with
        | leaf a =>
          dsimp [X_seq]
          exact hX a (by simp)
        | binary l r w h =>
          have h_valid : l.word ≠ [] ∧ r.word ≠ [] ∧
            w = l.word ++ r.word ∧ l.height + 1 ≤ h ∧ r.height + 1 ≤ h :=
            valid_binary h_ram
          obtain ⟨hl_ne, hr_ne, hw_eq, h_prev_l, h_prev_r⟩ := h_valid
          grind
        | nary cs w h =>
          have h_valid : cs ≠ [] ∧ (∀ c ∈ cs, c.word ≠ []) ∧
            w = List.flatten (cs.map FactorizationTree.word) ∧ ∀ c ∈ cs, c.height + 1 ≤ h := valid_nary h_ram
          obtain ⟨h_cs_ne, hc_ne, hw_eq, h_prev_c⟩ := h_valid
          have hc_mem := List.head_mem h_cs_ne
          have hc_prev := h_prev_c (cs.head h_cs_ne) hc_mem
          grind
      | succ n ih =>
        intro t' h_height ht' hX h_ram
        cases t' with
        | leaf a =>
          dsimp [X_seq]
          exact hX a (by simp)
        | binary l r w h =>
          have h_valid : l.word ≠ [] ∧ r.word ≠ [] ∧
            w = l.word ++ r.word ∧ l.height + 1 ≤ h ∧ r.height + 1 ≤ h :=
            valid_binary h_ram
          obtain ⟨hl_ne, hr_ne, hw_eq, h_prev_l, h_prev_r⟩ := h_valid
          have h_pos : 0 < h := by omega
          have hl_le_n : l.height ≤ n := by grind
          have hr_le_n : r.height ≤ n := by grind
          have h_ram_l : IsRamseyTree eval_T l := by
            cases h_ram with
            | binary hl hr => grind
          have h_ram_r : IsRamseyTree eval_T r := by
            cases h_ram with
            | binary hl hr => grind
          have hl_X : ∀ x ∈ l.word, x ∈ X :=
            fun x hx ↦ hX x (hw_eq ▸ List.mem_append.mpr (Or.inl hx))
          have hr_X : ∀ x ∈ r.word, x ∈ X :=
            fun x hx ↦ hX x (hw_eq ▸ List.mem_append.mpr (Or.inr hx))
          have hl_mem := ih l hl_le_n hl_ne hl_X h_ram_l
          have hr_mem := ih r hr_le_n hr_ne hr_X h_ram_r
          have hw_prod : listProdNE w ht' = listProdNE l.word hl_ne * listProdNE r.word hr_ne := by
            have h_concat_ne : l.word ++ r.word ≠ [] := by simp [hl_ne]
            have h_eq : listProdNE w ht' = listProdNE (l.word ++ r.word) h_concat_ne :=
              listProdNE_eq w (l.word ++ r.word) ht' h_concat_ne hw_eq
            rw [h_eq]
            exact listProdNE_concat _ _ hl_ne hr_ne
          have h_sub_l : X_seq ϕ X l.height ⊆ X_seq ϕ X (h - 1) := X_seq_mono ϕ X (by omega)
          have h_sub_r : X_seq ϕ X r.height ⊆ X_seq ϕ X (h - 1) := X_seq_mono ϕ X (by omega)
          have h_mul : listProdNE w ht' ∈ X_seq ϕ X (h - 1) * X_seq ϕ X (h - 1) := by
            rw [hw_prod]
            exact Set.mul_mem_mul (h_sub_l hl_mem) (h_sub_r hr_mem)
          have h_step : X_seq ϕ X (h - 1) * X_seq ϕ X (h - 1) ⊆ X_seq ϕ X h := by
            intro x hx
            have h_eq : h = (h - 1) + 1 := by omega
            rw [h_eq]
            exact Or.inl (Or.inr hx)
          exact h_step h_mul
        | nary cs w h =>
          have h_valid : cs ≠ [] ∧ (∀ c ∈ cs, c.word ≠ []) ∧
            w = List.flatten (cs.map FactorizationTree.word) ∧ ∀ c ∈ cs, c.height + 1 ≤ h := valid_nary h_ram
          obtain ⟨h_cs_ne, hc_ne, hw_eq, h_prev_c⟩ := h_valid
          have h_e : ∃ e : T, e * e = e ∧ ∀ c ∈ cs, eval_T c.word = e := by
            cases h_ram; rename_i h_len h_all he; exact he
          have hc_mem := List.head_mem h_cs_ne
          have hc_prev := h_prev_c (cs.head h_cs_ne) hc_mem
          have h_pos : 0 < h := by omega
          obtain ⟨e, he_idem, he_eval⟩ := h_e
          have h_h : h ≤ n + 1 := h_height
          have h_in_closure : listProdNE w ht' ∈ Subsemigroup.closure
            (X_seq ϕ X (h - 1) ∩ ϕ ⁻¹' {e}) := by
            exact listProdNE_bind_closure e (X_seq ϕ X (h - 1)) (cs.map FactorizationTree.word)
              (fun h_empty ↦ h_cs_ne (List.map_eq_nil_iff.mp h_empty))
              (fun c' hc' ↦ by
                obtain ⟨c, hc_in, rfl⟩ := List.mem_map.mp hc'
                exact hc_ne c hc_in)
              (fun c' hc' ↦ by
                obtain ⟨c, hc_in, rfl⟩ := List.mem_map.mp hc'
                exact he_eval c hc_in)
              (fun c' hc' ↦ by
                obtain ⟨c, hc_in, rfl⟩ := List.mem_map.mp hc'
                have hc_ram : IsRamseyTree eval_T c := by
                  cases h_ram; rename_i h_len h_all he; exact h_all c hc_in
                have hc_X : ∀ x ∈ c.word, x ∈ X := fun x hx ↦
                  hX x (hw_eq ▸ List.mem_flatten.mpr ⟨c.word, List.mem_map_of_mem hc_in, hx⟩)
                have h_mem_c := ih c (by have := h_prev_c c hc_in; omega) (hc_ne c hc_in) hc_X hc_ram
                exact X_seq_mono ϕ X (by have := h_prev_c c hc_in; omega) h_mem_c)
              w hw_eq ht'
          have h_step : (Subsemigroup.closure
            (X_seq ϕ X (h - 1) ∩ ϕ ⁻¹' {e}) : Set S) ⊆ X_seq ϕ X h := by
            intro x hx
            have h_eq : h = (h - 1) + 1 := by omega
            rw [h_eq]
            apply Or.inr
            simp only [mem_iUnion]
            exact ⟨e, he_idem, hx⟩
          exact h_step h_in_closure
    have ht_word_ne : t.word ≠ [] := ht_word.symm ▸ hu
    have ht_X : ∀ x ∈ t.word, x ∈ X := fun x hx ↦ huX x (ht_word ▸ hx)
    have h_mem := h_tree_mem_lem t.height t le_rfl ht_word_ne ht_X ht_ramsey
    have h_tree_mem : listProdNE u hu ∈ X_seq ϕ X (3 * nS T - 1) := by
      have h_eq : listProdNE u hu = listProdNE t.word ht_word_ne :=
        listProdNE_eq u t.word hu ht_word_ne ht_word.symm
      rw [h_eq]
      exact X_seq_mono ϕ X ht_height h_mem
    exact h_tree_mem
  · exact fun hs => X_seq_subset_closure ϕ X (3 * nS T - 1) hs

/-- Condition (1):
For all $a \in T$, $\{x \in X : \phi(x) = a\} \in P$. -/
def Cond1 (ϕ : S →ₙ* T) (X : Set S) (P : Set (Set S)) : Prop :=
  ∀ a : T, {x ∈ X | ϕ x = a} ∈ P

/-- Condition (1'):
If $A \subseteq B$ and $B \in P$, then $A \in P$ (down-closed / hereditary). -/
def Cond1' (P : Set (Set S)) : Prop :=
  ∀ ⦃A B : Set S⦄, A ⊆ B → B ∈ P → A ∈ P

/-- Condition (1''):
$X \in P$. -/
def Cond1'' (X : Set S) (P : Set (Set S)) : Prop :=
  X ∈ P

/-- Condition (2):
For all $A, B \in P$, $A \cup B \in P$. -/
def Cond2 (P : Set (Set S)) : Prop :=
  ∀ ⦃A B : Set S⦄, A ∈ P → B ∈ P → A ∪ B ∈ P

/-- Condition (3):
For all $A, B \in P$, $A * B \in P$. -/
def Cond3 (P : Set (Set S)) : Prop :=
  ∀ ⦃A B : Set S⦄, A ∈ P → B ∈ P → A * B ∈ P

/-- Condition (4):
For all $A \in P$, if $A \subseteq \phi^{-1}(\{e\})$ for an idempotent $e \in T$,
then $\langle A \rangle_S \in P$. -/
def Cond4 (ϕ : S →ₙ* T) (P : Set (Set S)) : Prop :=
  ∀ ⦃A : Set S⦄, A ∈ P → (∃ e : T, e * e = e ∧ A ⊆ ϕ ⁻¹' {e}) →
  (Subsemigroup.closure A : Set S) ∈ P

/-- `Cond1'` (down-closed) and `Cond1''` ($X \in P$) together imply `Cond1`. -/
lemma cond1_of_cond1'_and_cond1'' (ϕ : S →ₙ* T) (X : Set S) (P : Set (Set S))
    (h1' : Cond1' P) (h1'' : Cond1'' X P) : Cond1 ϕ X P := by
  intro a
  have h_sub : {x ∈ X | ϕ x = a} ⊆ X := fun x hx ↦ hx.1
  exact h1' h_sub h1''

omit [Semigroup S] in
/-- Finite union closure under `Cond2`:
If $P$ satisfies `Cond2` and $\emptyset \in P$, then any finite union of sets in $P$ is in $P$. -/
lemma finset_bUnion_mem_P (P : Set (Set S)) (h2 : Cond2 P) (h_empty : ∅ ∈ P)
    {α : Type*} (s : Finset α) (f : α → Set S) (hf : ∀ a ∈ s, f a ∈ P) :
    (⋃ a ∈ s, f a) ∈ P := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    simp [h_empty]
  | insert a s' ha ih =>
    simp only [Finset.mem_insert] at hf
    rw [Finset.set_biUnion_insert]
    exact h2 (hf _ (Or.inl rfl)) (ih (fun b hb ↦ hf b (Or.inr hb)))

/-- **Set-Family Fixed Point Theorem**:
Let $S$ be a semigroup, $\phi : S →ₙ* T$ a semigroup morphism to a
finite semigroup $T$, and $X ⊆ S$. If $P \subseteq \mathcal{P}(S)$
satisfies conditions (1)-(4) (and down-closedness `Cond1'`),
then $\langle X \rangle_S \in P$. -/
theorem closure_mem_set_family [Finite T] [Nonempty T] (ϕ : S →ₙ* T) (X : Set S) (P : Set (Set S))
    (h1' : Cond1' P)
    (h1 : Cond1 ϕ X P)
    (h2 : Cond2 P)
    (h3 : Cond3 P)
    (h4 : Cond4 ϕ P) :
    (Subsemigroup.closure X : Set S) ∈ P := by
  haveI := Fintype.ofFinite T
  have h_Xn : ∀ n, X_seq ϕ X n ∈ P := by
    intro n
    induction n with
    | zero =>
      dsimp [X_seq]
      have h_eq : X = ⋃ a : T, {x ∈ X | ϕ x = a} := by
        ext x
        simp only [mem_iUnion, mem_sep_iff]
        exact ⟨fun hx ↦ ⟨ϕ x, hx, rfl⟩, fun ⟨a, hx, _⟩ ↦ hx⟩
      rw [h_eq]
      have h_empty : ∅ ∈ P := by
        have a : T := Classical.arbitrary T
        have h_sub : ∅ ⊆ {x ∈ X | ϕ x = a} := empty_subset _
        exact h1' h_sub (h1 a)
      have h_eq' :
        (⋃ a : T, {x ∈ X | ϕ x = a}) = ⋃ a ∈ (Finset.univ : Finset T), {x ∈ X | ϕ x = a} := by
        ext x; simp
      rw [h_eq']
      exact finset_bUnion_mem_P P h2 h_empty Finset.univ _ (fun a _ ↦ h1 a)
    | succ n ih =>
      dsimp [X_seq]
      refine h2 (h2 ih (h3 ih ih)) ?_
      have h_empty : ∅ ∈ P := by
        have : ∅ ⊆ X_seq ϕ X n := empty_subset _
        exact h1' this ih
      have h_eq' : (⋃ (e : T) (_ : e * e = e),
        (Subsemigroup.closure (X_seq ϕ X n ∩ ϕ ⁻¹' {e}) : Set S)) =
        ⋃ e ∈ (Finset.univ : Finset T), ⋃ (_ : e * e = e),
        (Subsemigroup.closure (X_seq ϕ X n ∩ ϕ ⁻¹' {e}) : Set S) := by
        ext x
        simp
      rw [h_eq']
      refine finset_bUnion_mem_P P h2 h_empty Finset.univ _ (fun e _ ↦ ?_)
      by_cases he : e * e = e
      · simp only [he, iUnion_true]
        have h_inter : X_seq ϕ X n ∩ ϕ ⁻¹' {e} ∈ P :=
          h1' inter_subset_left ih
        have h_sub_e : X_seq ϕ X n ∩ ϕ ⁻¹' {e} ⊆ ϕ ⁻¹' {e} := inter_subset_right
        exact h4 h_inter ⟨e, he, h_sub_e⟩
      · simp only [he, iUnion_false]
        exact h_empty
  rw [closure_eq_X_seq ϕ X]
  exact h_Xn (3 * nS T - 1)

/-- The fiber subsemigroup of an idempotent $e \in T$ under a morphism `f`. -/
def fiberSubsemigroup (f : S →ₙ* T) (e : T) (he : e * e = e) : Subsemigroup S where
  carrier := f ⁻¹' {e}
  mul_mem' {x y} hx hy := by
    simp only [mem_preimage, mem_singleton_iff] at hx hy ⊢
    rw [f.map_mul, hx, hy, he]

/-- **Brown's Lemma**:
Let `f : S →ₙ* T` be a semigroup morphism. If `T` is locally finite
and for every idempotent `e ∈ T`, the fiber subsemigroup `f ⁻¹' {e}` is locally finite,
then `S` is locally finite. -/
theorem brown_lemma (f : S →ₙ* T)
    (hT : IsLocallyFinite T)
    (h_fibers : ∀ (e : T) (he : e * e = e), IsLocallyFinite (fiberSubsemigroup f e he)) :
    IsLocallyFinite S := by
  intro X hX
  by_cases hX_ne : X.Nonempty
  · obtain ⟨x0, hx0⟩ := hX_ne
    let S' := Subsemigroup.closure X
    let T' := Subsemigroup.closure (f '' X)
    have hT'_fin : (T' : Set T).Finite := hT (f '' X) (hX.image f)
    haveI : Fintype T' := hT'_fin.fintype
    have hT'_nonempty : Nonempty T' :=
      ⟨⟨f x0, Subsemigroup.subset_closure (mem_image_of_mem f hx0)⟩⟩
    haveI : Nonempty (Fin (nS T')) := instNonemptyFin_nS
    let f' : S' →ₙ* T' := {
      toFun := fun ⟨x_val, hx⟩ ↦ ⟨f x_val, by
        induction hx using Subsemigroup.closure_induction with
        | mem a ha => exact Subsemigroup.subset_closure (mem_image_of_mem f ha)
        | mul a b ha hb iha ihb =>
          rw [f.map_mul]
          exact Subsemigroup.mul_mem _ iha ihb⟩
      map_mul' := fun x y ↦ Subtype.ext (f.map_mul x.1 y.1)
    }
    let P : Set (Set S') := { A | A.Finite }
    have h1' : Cond1' P := fun A B hAB hB ↦ hB.subset hAB
    let X_S' : Set S' := range (fun (x : X) ↦ (⟨x.1, Subsemigroup.subset_closure x.2⟩ : S'))
    have h1'' : Cond1'' X_S' P := by
      dsimp [Cond1'', P, X_S']
      haveI : Fintype X := hX.fintype
      exact Set.finite_range _
    have h1 : Cond1 f' X_S' P :=
      cond1_of_cond1'_and_cond1'' f' _ P h1' h1''
    have h2 : Cond2 P := fun A B hA hB ↦ hA.union hB
    have h3 : Cond3 P := fun A B hA hB ↦ Set.Finite.mul hA hB
    have h4 : Cond4 f' P := by
      intro A hA ⟨e', he', hAe'⟩
      have hA_sub_fiber : ∀ x ∈ A, f x.1 = e'.1 := by
        intro x hx
        have : f' x = e' := hAe' hx
        exact Subtype.ext_iff.mp this
      have h_idem : e'.1 * e'.1 = e'.1 := Subtype.ext_iff.mp he'
      have h_lf := h_fibers e'.1 h_idem
      let A_fiber : Set (fiberSubsemigroup f e'.1 h_idem) :=
        { a | ∃ x ∈ A, a.1 = x.1 }
      have hA_fiber_fin : A_fiber.Finite := by
        let g : A_fiber → A := fun ⟨a, ha⟩ ↦
          have hx : ∃ x ∈ A, a.1 = x.1 := ha
          ⟨Classical.choose hx, (Classical.choose_spec hx).1⟩
        have hg_inj : Function.Injective g := by
          intro ⟨a1, ha1⟩ ⟨a2, ha2⟩ hg
          have h_eq : (g ⟨a1, ha1⟩).1.1 = (g ⟨a2, ha2⟩).1.1 := congrArg (fun x ↦ x.1.1) hg
          have h1 : (g ⟨a1, ha1⟩).1.1 = (Classical.choose (ha1 : ∃ x ∈ A, a1.1 = x.1)).1 := rfl
          have h2 : (g ⟨a2, ha2⟩).1.1 = (Classical.choose (ha2 : ∃ x ∈ A, a2.1 = x.1)).1 := rfl
          have h3 : (Classical.choose (ha1 : ∃ x ∈ A, a1.1 = x.1)).1 = a1.1 :=
            (Classical.choose_spec (ha1 : ∃ x ∈ A, a1.1 = x.1)).2.symm
          have h4 : (Classical.choose (ha2 : ∃ x ∈ A, a2.1 = x.1)).1 = a2.1 :=
            (Classical.choose_spec (ha2 : ∃ x ∈ A, a2.1 = x.1)).2.symm
          have h_a1_a2 : a1.1 = a2.1 := by rw [← h3, ← h1, h_eq, h2, h4]
          exact Subtype.ext (Subtype.ext h_a1_a2)
        haveI : Finite A := hA.to_subtype
        haveI : Finite A_fiber := Finite.of_injective g hg_inj
        exact Set.toFinite A_fiber
      have h_closure_fin := h_lf A_fiber hA_fiber_fin
      have hA_sub_fiber_closure : ∀ x ∈ Subsemigroup.closure A, f x.1 = e'.1 := by
        intro x hx
        induction hx using Subsemigroup.closure_induction with
        | mem y hy => exact hA_sub_fiber y hy
        | mul y z hy hz ihy ihz =>
          change f (y.1 * z.1) = e'.1
          rw [f.map_mul, ihy, ihz, h_idem]
      let g : ↥(Subsemigroup.closure A) → ↥(Subsemigroup.closure A_fiber) :=
        fun ⟨x, hx⟩ ↦
          let a_val : fiberSubsemigroup f e'.1 h_idem := ⟨x.1, hA_sub_fiber_closure x hx⟩
          have ha_mem : a_val ∈ Subsemigroup.closure A_fiber := by
            induction hx using Subsemigroup.closure_induction with
            | mem y hy =>
              apply Subsemigroup.subset_closure
              exact ⟨y, hy, rfl⟩
            | mul y z hy hz ihy ihz =>
              exact Subsemigroup.mul_mem _ ihy ihz
          ⟨a_val, ha_mem⟩
      have hg_inj : Function.Injective g := by
        intro ⟨x1, hx1⟩ ⟨x2, hx2⟩ hg
        have h_eq : (g ⟨x1, hx1⟩).1.1 = (g ⟨x2, hx2⟩).1.1 := congrArg (fun x ↦ x.1.1) hg
        exact Subtype.ext (Subtype.ext h_eq)
      haveI : Finite ↥(Subsemigroup.closure A_fiber) := h_closure_fin.to_subtype
      haveI : Finite ↥(Subsemigroup.closure A) := Finite.of_injective g hg_inj
      exact Set.toFinite _
    have h_closure_P := closure_mem_set_family f' _ P h1' h1 h2 h3 h4
    have h_S'_fin : Finite S' := by
      have h_univ : (Subsemigroup.closure X_S' : Set S') = Set.univ := by
        ext ⟨s, hs⟩
        simp only [Set.mem_univ, iff_true]
        induction hs using Subsemigroup.closure_induction with
        | mem x hx =>
          exact Subsemigroup.subset_closure ⟨⟨x, hx⟩, rfl⟩
        | mul x y hx hy ihx ihy =>
          exact Subsemigroup.mul_mem _ ihx ihy
      have h_univ_P : Set.univ ∈ P := h_univ ▸ h_closure_P
      haveI : Finite ↥(Set.univ : Set S') := h_univ_P.to_subtype
      let u_f : S' → ↥(Set.univ : Set S') := fun x ↦ ⟨x, trivial⟩
      have hu_f : Function.Injective u_f := fun x y h ↦ Subtype.ext_iff.mp h
      exact Finite.of_injective u_f hu_f
    exact Set.toFinite _
  · have hX_empty : X = ∅ := not_nonempty_iff_eq_empty.mp hX_ne
    rw [hX_empty]
    simp only [Subsemigroup.closure_empty]
    exact finite_empty

end BrownLemma
